---

dist: xenial
sudo: required

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache

env:
  global:
    # Environment variables for packaging
    - PRODUCT=flameshot
    - VERSION=0.6.0
    - RELEASE=1
    - ARCH=x86_64
    - SNAP_DOCKER_REPO="snapcore/snapcraft"
    - FLATPAK_DOCKER_REPO="vitzy/flameshot:fedora-28"

matrix:
  include:
    - os: linux
      env: OS=ubuntu DIST=xenial EXTEN=appimage
      language: cpp
    - os: linux
      env: OS=ubuntu DIST=xenial EXTEN=snap
      services: docker
      language: cpp
    - os: linux
      env: OS=fedora DIST=28 EXTEN=flatpak RUN_TIME=kde
      services: docker
      language: cpp
      # - os: linux
      #   env: OS=fedora DIST=28 EXTEN=flatpak RUN_TIME=gnome
      #   services: docker
      #   language: cpp
      # - os: linux
      #   env: OS=fedora DIST=28 EXTEN=flatpak RUN_TIME=freedesktop
      #   services: docker
before_install:
  - export ROOT_PATH="$(pwd)"
  - git clone https://github.com/lupoDharkael/flameshot
  - export SRC_PATH="${ROOT_PATH}/flameshot"
  - chmod +x ${ROOT_PATH}/scripts/*.sh
  - chmod +x ${ROOT_PATH}/scripts/services/*.sh
  - |
    case "${EXTEN}" in
      "appimage")
        source ${ROOT_PATH}/scripts/appimage_before_install.sh
        ;;
      "snap")
        source ${ROOT_PATH}/scripts/snap_before_install.sh
        ;;
      "flatpak")
        source ${ROOT_PATH}/scripts/flatpak_before_install.sh
        ;;
    esac

install:
  - |
    case "${EXTEN}" in
      "appimage")
        source ${ROOT_PATH}/scripts/appimage_install.sh
        ;;
      "snap")
        source ${ROOT_PATH}/scripts/snap_install.sh
        ;;
      "flatpak")
        source ${ROOT_PATH}/scripts/flatpak_install.sh
        ;;
    esac

script:
  - |
    case "${EXTEN}" in
      "appimage")
        source ${ROOT_PATH}/scripts/appimage_script.sh
        ;;
      "snap")
        source ${ROOT_PATH}/scripts/snap_script.sh
        ;;
      "flatpak")
        source ${ROOT_PATH}/scripts/flatpak_script.sh
        ;;
    esac
  - pwd && ls

after_success:
  - |
    case "${EXTEN}" in
      "appimage")
        source ${ROOT_PATH}/scripts/appimage_after_success.sh
        ;;
      "snap")
        source ${ROOT_PATH}/scripts/snap_after_success.sh
        ;;
    esac
